/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef GAMEOFLIFE_PRIVATE_H
#define GAMEOFLIFE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"1.0.0.40"
#define VER_MAJOR	1
#define VER_MINOR	0
#define VER_RELEASE	0
#define VER_BUILD	40
#define COMPANY_NAME	""
#define FILE_VERSION	"1.0.0.40"
#define FILE_DESCRIPTION	"Developed using the Dev-C++ IDE"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"1.0.0.40"

#endif /*GAMEOFLIFE_PRIVATE_H*/
